export const ADMIN_ROUTE = '/admin'
export const MANAGER_ROUTE = '/manager'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const MAIN_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const TOURS_ROUTE = '/tours'
export const ONETOUR_ROUTE = '/tours'

export const FAQ_ROUTE = '/FAQ'
export const SUPPORT_ROUTE = '/support'
export const USER_ROUTE = '/profile'